$primary = rgb(c2c1ff)
$surface = rgba(13131699)
$surface_lowest = rgba(0e0e11cc)
$text = rgb(cdd6f4)
$subtext = rgb(6c6f85)

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/art002e009285~large.jpg
    blur_size = 4
    blur_passes = 3
    brightness = 0.5
    vibrancy = 0.1696
}

image {
    monitor =
    path = ~/.face
    size = 80
    rounding = -1
    border_size = 2
    border_color = $primary
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $text
    font_size = 72
    font_family = Sans Serif Bold
    position = 0, 240
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $subtext
    font_size = 16
    font_family = Sans Serif
    position = 0, 170
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.15
    dots_center = true
    outer_color = $surface_lowest
    inner_color = $surface
    font_color = $text
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i>Password</i>
    hide_input = false
    rounding = 12
    check_color = $primary
    fail_color = rgb(ffb4ab)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    capslock_color = rgb(e9b9d2)
    position = 0, 400
    halign = center
    valign = bottom
}
