general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = /home/joaommartins/.config/hypr/scripts/post-resume.sh
    unlock_cmd = loginctl unlock-session # avoid HDMI monitor from freezing
    ignore_dbus_inhibit = false
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = brightnessctl -r
}

listener {
    timeout = 330
    on-timeout = sleep 1 && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 360
    on-timeout = systemctl suspend
}
